version: '3'
services:
  cakephp4:
    build: ./cakephp4
    image: cake4-sample
    container_name: cake4-sample
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - ./src:/srv/httpd

  mysql:
    build: ./mysql
    image: cake4-mysql
    container_name: cake4-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: lamp_test
      MYSQL_USER: dockeruser
      MYSQL_PASSWORD: dockeruser
    volumes:
      - ./mysql/data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: cake4-mailhog
    ports:
      - "1080:8025"
